import * as stylex from "@stylexjs/stylex";
import { borderRadius, colors, shadows } from "./theme.stylex";

const styles = stylex.create({
  sidebar: {
    width: "clamp(5rem, 6vw, 6rem)",
    backgroundColor: colors.sidebarBg,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: "2rem",
    paddingBottom: "2rem",
    zIndex: 20,
    flexShrink: 0,
    height: "100%",
    position: "fixed",
    left: 0,
    top: 0,
  },
  logoWrapper: {
    marginBottom: "2.5rem",
    padding: "0.5rem",
  },
  logo: {
    width: "2.5rem",
    height: "2.5rem",
    borderRadius: "0.75rem",
    backgroundImage: `linear-gradient(135deg, ${colors.primary}, ${colors.secondary})`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: colors.textLight,
    fontWeight: 700,
    fontSize: "1.25rem",
    boxShadow: shadows.soft,
  },
  nav: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "1.5rem",
    width: "100%",
    paddingLeft: "1rem",
    paddingRight: "1rem",
  },
  navItemBase: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    aspectRatio: "1 / 1",
    borderRadius: borderRadius.default,
    textDecoration: "none",
    transitionProperty: "transform, background-color, color",
    transitionDuration: "150ms",
    transitionTimingFunction: "ease",
    position: "relative",
  },
  navItemActive: {
    backgroundColor: colors.primary,
    color: colors.sidebarIcon,
    boxShadow: shadows.soft,
  },
  navItemActiveHover: {
    transform: "scale(1.05)",
  },
  navItemInactive: {
    color: "#9ca3af",
  },
  navItemInactiveHover: {
    color: colors.sidebarIcon,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  tooltip: {
    position: "absolute",
    left: "3.5rem",
    backgroundColor: "#1f2937",
    color: "#ffffff",
    fontSize: "0.75rem",
    padding: "0.25rem 0.5rem",
    borderRadius: "0.5rem",
    opacity: 0,
    transition: "opacity 150ms ease",
    pointerEvents: "none",
    whiteSpace: "nowrap",
    zIndex: 50,
  },
  tooltipVisible: {
    opacity: 1,
  },
  tooltipHidden: {
    opacity: 0,
  },
  icon: {
    fontSize: "1.5rem",
    lineHeight: 1,
  },
  footer: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    paddingLeft: "1rem",
    paddingRight: "1rem",
    width: "100%",
    marginTop: "auto",
  },
  logoutButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    aspectRatio: "1 / 1",
    borderRadius: borderRadius.default,
    color: "#9ca3af",
    transitionProperty: "color, background-color",
    transitionDuration: "150ms",
    transitionTimingFunction: "ease",
  },
  logoutButtonHover: {
    color: "#f87171",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
});

export default styles;
